<a href="https://colab.research.google.com/github/anvithapo99/DA-and-ML-workshop/blob/master/Day_3_Session_2_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

#1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
#tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

[ ]
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)


0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [3]:
#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type
[ ]
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


In [4]:
#3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [5]:
#4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [6]:
#5.Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [7]:
#6.Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [9]:
#7.Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


In [10]:
#8.Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [11]:
#9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


In [18]:
#10.Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [19]:
#11.Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields.

import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [22]:
#15.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.78987197 0.11264535 0.72168421 0.17436828]
 [0.05859073 0.37089867 0.89472532 0.29474085]
 [0.69906113 0.26503509 0.45539579 0.04888875]
 [0.25781488 0.60675329 0.98293788 0.157778  ]]


In [23]:
#16.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.60593325 0.24571223 0.20653403 0.1589129  0.18955492 0.56579094
  0.08786241 0.94992357 0.36283671 0.80670615]
 [0.12123843 0.16092533 0.37835617 0.74824216 0.07441071 0.13721905
  0.14682363 0.16662241 0.12287426 0.04160409]
 [0.80119374 0.37215567 0.05210892 0.38170313 0.02424994 0.89607051
  0.40794258 0.3316103  0.35593525 0.72209851]
 [0.11710633 0.18865698 0.38810606 0.68473268 0.6841641  0.12900447
  0.86674666 0.05720348 0.62845126 0.48359657]
 [0.63027189 0.91364659 0.95243906 0.03811542 0.15237561 0.12901231
  0.73878521 0.45215477 0.7154683  0.44637301]
 [0.4201863  0.07618993 0.26982006 0.04224037 0.94595292 0.39480401
  0.05984067 0.05412332 0.10801417 0.38617715]
 [0.44779737 0.75623595 0.39798427 0.23060679 0.97553555 0.25677547
  0.11265799 0.85369569 0.13371328 0.15046573]
 [0.40977796 0.94692553 0.42410389 0.90971988 0.60689632 0.67860414
  0.27489664 0.65473587 0.32163185 0.29916146]
 [0.02752994 0.17394353 0.37449029 0.99635715 0.00937986 0.86943

In [24]:
#17.Write a NumPy program to generate 8 random integers between 100 and 300

import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[180 109 190 226 108 241 273 243]


In [25]:
#18.Write a NumPy program to create a random integer nos of size 20 and sort it

import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.70320165 0.91458986 0.84443624 0.68448084 0.33635733 0.6231962
 0.97317406 0.32921213 0.81513478 0.86695654 0.76975229 0.58028774
 0.9096199  0.19570622 0.02794903 0.64164688 0.78279029 0.29775507
 0.66491272 0.07627896]
Sorted array:
[0.02794903 0.07627896 0.19570622 0.29775507 0.32921213 0.33635733
 0.58028774 0.6231962  0.64164688 0.66491272 0.68448084 0.70320165
 0.76975229 0.78279029 0.81513478 0.84443624 0.86695654 0.9096199
 0.91458986 0.97317406]
